language: minimal

addons:
  apt:
    packages:
      - luarocks

install: luarocks install --local luacheck

before_script:
#  - /home/travis/.luarocks/bin/luacheck . --no-color -q

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -p 18988 -g 1.13.5

notifications:
  email:
    on_success: never
    on_failure: always